config/routes.rb
MediatainmentProductionsTemplate::Application.routes.draw do

  mount Mercury::Engine => '/'

  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    get '/editor(/*requested_uri)' => "mercury#edit", :as => :mercury_editor

    resources :articles

    resources :categories

    resources :roles

    devise_for :users,
               path: "",
               :controllers => {
                   :registrations => "registrations",
                   :sessions => "sessions",
                   :confirmations => "confirmations",
                   :passwords => "passwords"},
               path_names: {
                   sign_in: 'login',
                   sign_up: 'register',
                   sign_out: 'logout',
                   unlock: 'unlock',
                   confirmation: 'confirm',
                   password: 'password'
               }

    resources :users

    match 'index' => 'index#index', as: :index, via: [:get]
    match 'contact' => 'email#contact_form', as: :contact, via: [:get, :post]

    root to: 'index#index'

  end

end

app/models/role.rb
class Role < ActiveRecord::Base

  extend FriendlyId

  attr_accessible :name, :roles, :role_id

  has_and_belongs_to_many :users

  validates_presence_of :name
  before_destroy :do_not_change_admin_role
  before_update :do_not_change_admin_role

  friendly_id :name, use: :slugged

  private

  def do_not_change_admin_role
    errors.add(:base, "Admin Role cannot be changed") if name == 'admin' || name_change.include?('admin')
    errors.blank? #return false, to not destroy the element, otherwise, it will delete.
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  load_and_authorize_resource

  before_filter :set_role, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
  end

  def create
    @role = Role.new(params[:role])
    @role.save
    respond_with(@role)
  end

  def update
    @role.update_attributes(params[:role])
    respond_with(@role)
  end

  def destroy
    @role.destroy
    respond_with(@role)
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
    <%= errors_for @role %>

    <div class="field">
      <%= f.bootstrap_text_field :name, label: t('name') %>
    </div>
    <div class="actions">
      <%= f.submit t('submit'), class: 'btn btn-default' %>
    </div>
<% end %>

app/views/roles/edit.html.erb
<h1><%= t('edit_resource', resource: t('role')) %></h1>

<%= render 'form' %>

<%= link_to t('show'), @role, class: 'btn btn-default' %> |
<%= link_to t('back'), roles_path, class: 'btn btn-default' %>

app/views/roles/index.html.erb
<% breadcrumb :roles %>

<h1><%= t('roles') %></h1>

<table class="table table-bordered">
  <tr>
    <th><%= t('name') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to t('show'), role %></td>
    <td><%= link_to t('edit'), edit_role_path(role) %></td>
    <td><%= link_to t('destroy'), role, method: :delete, data: { confirm: t('are_you_sure') } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('new_resource', resource: t('role')), new_role_path, class: 'btn btn-default' %>

app/views/roles/new.html.erb
<h1><%= t('new_resource', resource: t('role')) %></h1>

<%= render 'form' %>

<%= link_to t('back'), roles_path, class: 'btn btn-default' %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('name') %>:</b>
  <%= @role.name %>
</p>

<%= link_to t('edit'), edit_role_path(@role), class: 'btn btn-default' %> |
<%= link_to t('back'), roles_path , class: 'btn btn-default'%>